"""
PHASE 3 CHECKPOINT (branch `video-gen-fidelity`), zero additional Wan spend --
re-assembles the REAL clips already generated by the earlier full-pipeline
live run (derisk/outputs/full_pipeline_live_result.json) through the UPDATED
`agents.assembly_agent` (never hard-trim the last segment's tail, burn an
end-of-cut fade, prefer start-trim for mid-ad human-interaction shots) and
produces a new local master cut to inspect.

Reuses the real shot_list/generated_shots/voiceover/winning_script recorded
in that JSON verbatim -- the shot clip / VO audio / captions URLs are still
live (OSS-signed, ~20h TTL remaining at the time this was written), so this
downloads real, already-billed assets rather than regenerating anything.

Usage (from backend/):
    python -m derisk.test_phase3_checkpoint_reassemble
"""
from __future__ import annotations

import asyncio
import json
import subprocess
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent.parent / ".env")

from agents.assembly_agent import _assemble_master_cut_impl  # noqa: E402

OUTPUTS_DIR = Path(__file__).resolve().parent / "outputs"
RESULT_JSON = OUTPUTS_DIR / "full_pipeline_live_result.json"


def _ffprobe_duration(path: str) -> float:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", path],
        capture_output=True, text=True, check=True,
    )
    return float(out.stdout.strip())


def _extract_frame(video_path: str, out_path: Path, t: float) -> None:
    subprocess.run(
        ["ffmpeg", "-y", "-ss", str(t), "-i", video_path, "-frames:v", "1", str(out_path)],
        check=True, capture_output=True,
    )


async def main() -> int:
    data = json.loads(RESULT_JSON.read_text(encoding="utf-8"))
    shot_list = data["shot_list"]
    generated_shots = data["generated_shots"]
    voiceover = data["voiceover"]
    winning_script = data["winning_script"]

    print(f"Loaded real job: {len(shot_list)} shots, {len(generated_shots)} generated clips.")
    print(f"Winning script has {len(winning_script['beats'])} beats; last beat: {winning_script['beats'][-1]['line']!r}")

    captured_path = str(OUTPUTS_DIR / "phase3_checkpoint_reassembled.mp4")

    def _upload(local_path: str) -> str:
        import shutil
        shutil.copy(local_path, captured_path)
        return "local://reassembled"

    print("\n=== Re-assembling through the UPDATED assembly_agent (real ffmpeg, real downloads) ===")
    result = await _assemble_master_cut_impl(
        shot_list, generated_shots, voiceover, winning_script, "phase3-reassemble-checkpoint",
        upload_fn=_upload,
    )
    print(f"  shot_count={result.shot_count}  total_duration_sec={result.total_duration_sec}")
    print(f"  degraded_beats={result.degraded_beats}")
    print(f"  saved -> {captured_path}")

    real_duration = _ffprobe_duration(captured_path)
    print(f"\n  ffprobe real duration: {real_duration:.3f}s")

    print("\n=== Extracting the final 3 seconds as frames ===")
    for i, t in enumerate([real_duration - 3.0, real_duration - 1.5, real_duration - 0.3]):
        t = max(0.0, t)
        out_path = OUTPUTS_DIR / f"phase3_checkpoint_ending_{i}_t{t:.2f}s.jpg"
        _extract_frame(captured_path, out_path, t)
        print(f"  frame -> {out_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
